import { describe, expect, test } from "bun:test";
import { readFile } from "node:fs/promises";
import { gunzipSync } from "node:zlib";
import { join } from "node:path";

const root = join(import.meta.dir, "..");

describe("production bundle", () => {
  test("loads the terminal styles, Sheltie favicon and authentication UI", async () => {
    const html = await readFile(join(root, "dist/index.html"), "utf8");
    expect(html).toContain('href="/client.css"');
    expect(html).toContain('href="/style.css"');
    expect(html).toContain('sizes="16x16" href="/favicon-16.png"');
    expect(html).toContain('sizes="32x32" href="/favicon-32.png"');
    expect(html).toContain('sizes="64x64" href="/favicon-64.png"');
    expect(html).toContain('type="image/svg+xml" sizes="any" href="/favicon.svg"');
    expect(html).toContain('<img src="/favicon.svg"');
    expect(html).toContain('rel="apple-touch-icon" href="/favicon.png"');
    expect(html).toContain('id="auth-form"');
    expect(html).toContain('id="terminal"');
    expect(html).toContain('id="sheltie-peek" aria-hidden="true"');
    expect(html).toContain('<use href="/favicon.svg#sheltie-head"');
    expect(html).toContain('id="settings-version"');
    expect(await Bun.file(join(root, "dist/client.css")).exists()).toBe(true);
    expect(await Bun.file(join(root, "dist/client.js")).exists()).toBe(true);
    expect(await Bun.file(join(root, "dist/favicon.png")).exists()).toBe(true);
    expect(await Bun.file(join(root, "dist/favicon-16.png")).exists()).toBe(true);
    expect(await Bun.file(join(root, "dist/favicon-32.png")).exists()).toBe(true);
    expect(await Bun.file(join(root, "dist/favicon-64.png")).exists()).toBe(true);
    const styles = await readFile(join(root, "dist/style.css"), "utf8");
    expect(styles).toContain(".document-link-indicators span { position: absolute; box-sizing: border-box; border-bottom: 2px solid #31bafd;");
    expect(styles).toContain("@media (hover: none) and (pointer: coarse)");
    expect(styles).toContain("height: var(--shelt-viewport-height, 100%);");
    expect(styles).toContain("top: var(--shelt-viewport-top, 0);");
    expect(styles).toContain("touch-action: pinch-zoom;");
    expect(styles).not.toContain("touch-action: none;");
    expect(styles).not.toContain("border-bottom: 2px solid transparent");
  });

  test("ships the vector icon source and correctly sized PNG fallbacks", async () => {
    const source = await readFile(join(root, "public/favicon.svg"), "utf8");
    expect(await readFile(join(root, "dist/favicon.svg"), "utf8")).toBe(source);
    expect(source).toContain('xmlns="http://www.w3.org/2000/svg"');
    expect(source).toContain('viewBox="0 0 512 512"');
    expect(source).toContain("Shetland Sheepdog");
    expect(source).toContain('<g id="sheltie-head">');
    expect(source).toContain("<path ");
    expect(source).not.toMatch(/<(?:image|script|foreignObject)\b|\b(?:href|onload)=/i);
    for (const size of [512, 64, 32, 16]) {
      const file = size === 512 ? "favicon.png" : `favicon-${size}.png`;
      const png = await readFile(join(root, "dist", file));
      expect(png.equals(await readFile(join(root, "public", file)))).toBe(true);
      expect(png.subarray(0, 8)).toEqual(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]));
      expect(png.readUInt32BE(16)).toBe(size);
      expect(png.readUInt32BE(20)).toBe(size);
    }
  });

  test("ships preview assets without loading Mermaid in the terminal bundle", async () => {
    const html = await readFile(join(root, "dist/preview.html"), "utf8");
    const styles = await readFile(join(root, "dist/preview.css"), "utf8");
    const client = await readFile(join(root, "dist/client.js"), "utf8");
    const preview = await readFile(join(root, "dist/preview.js"), "utf8");
    expect(html).toContain('type="image/svg+xml" sizes="any" href="/favicon.svg"');
    expect(html).toContain('id="preview"');
    expect(html).toContain('id="tts-toolbar" class="tts-toolbar collapsed"');
    expect(html).toContain('id="tts-toggle"');
    expect(html).toContain('aria-expanded="false"');
    expect(html).toContain('id="tts-controls"');
    expect(html).toContain('id="tts-start"');
    expect(html).toContain('id="tts-target"');
    expect(html).not.toContain('id="tts-mode"');
    expect(html).not.toContain('value="local"');
    expect(html).not.toContain('id="tts-play-here"');
    expect(html).toContain('id="toc-panel"');
    expect(html).toContain('id="toc-toggle"');
    expect(html).toContain('id="toc-list"');
    expect(html).toContain('aria-label="文档目录"');
    expect(html).toContain('aria-label="文档目录树"');
    expect(html).toContain('src="/preview.js"');
    expect(styles).toContain(".tts-toolbar { position: fixed;");
    expect(styles).toContain(".tts-toolbar.collapsed { padding: 0;");
    expect(styles).toContain(".tts-toolbar.collapsed .tts-controls { display: none;");
    expect(styles).toContain(".tts-toolbar .tts-toggle { display: grid;");
    expect(styles).toContain("backdrop-filter: blur(18px) saturate(150%);");
    expect(styles).not.toContain(".tts-play-here");
    expect(styles).toContain(".tts-speaking {");
    expect(styles).toContain(".toc-panel {");
    expect(styles).toContain(".toc-toggle {");
    expect(styles).toContain(".toc-list {");
    expect(styles).toContain(".toc-tree {");
    expect(styles).toContain(".toc-link {");
    expect(styles).toContain(".toc-link.toc-active {");
    expect(styles).toContain(".toc-item.toc-item-l2 > .toc-link");
    expect(styles).toContain(".toc-item.toc-item-l3 > .toc-link");
    expect(styles).toContain("scroll-margin-top: 80px;");
    expect(styles).toContain(".markdown-body { width: min(1600px, calc(100% - 48px));");
    expect(styles).toContain("overflow-wrap: break-word;");
    expect(styles).toContain(".table-wrap { max-width: 100%; overflow-x: auto; }");
    expect(styles).toContain("@media (max-width: 900px)");
    expect(styles).toContain(".markdown-body table { min-width: 900px; }");
    expect(styles).not.toContain("width: min(980px, calc(100% - 48px))");
    expect(preview.length).toBeGreaterThan(100_000);
    expect(client).not.toContain("Unsupported Mermaid diagram");
    expect(client).not.toContain('output:"mathml"');
    expect(client).toContain('addEventListener("touchstart"');
    expect(client).toContain('addEventListener("touchmove"');
    expect(client).toContain('new WheelEvent("wheel"');
    expect(client).toContain("visualViewport");
    expect(client).toContain("--shelt-viewport-height");
    expect(client).toContain('type:"resize"');
    expect(client).toContain('type:"output-ack"');
    expect(client).toContain("Terminal output exceeded browser capacity");
    expect(client).toContain("onBinary");
    expect(client).toContain("requestAnimationFrame");
    expect(client).not.toContain("previousSocket");
    expect(preview).toContain("Unsupported Mermaid diagram");
    expect(preview).toContain('output:"mathml"');
    expect(preview).toContain('fetch("/api/tts"');
    expect(preview).toContain("fetchTtsAudio");
    expect(preview).toContain("setExpanded");
    expect(preview).toContain("收起语音朗读工具栏");
    expect(preview).not.toContain("shelt-tts-mode");
    expect(preview).not.toContain("speechSynthesis");
    expect(preview).not.toContain("正在使用本地系统语音朗读");
    expect(preview).toContain("图片预览未启用 OCR 识别");
    expect(preview).toContain("allow-same-origin");
    expect(gunzipSync(await readFile(join(root, "dist/client.js.gz"))).toString()).toBe(client);
    expect(gunzipSync(await readFile(join(root, "dist/preview.js.gz"))).toString()).toBe(preview);
  });
});
